// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZs0WVeZt91hc4fQtfuTg4kY4-bFq9qw',
    appId: '1:222422545919:web:6c595ab40b37a49e41e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    authDomain: 'development-e5282.firebaseapp.com',
    storageBucket: 'development-e5282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDazdc6VhXTuYP23LivAzjLiJBU9ap8jUg',
    appId: '1:222422545919:android:15dbcb59093cb5fd41e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    storageBucket: 'development-e5282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3P2kuByZkIO2G_mG9zj_t0UKJfzcsdUU',
    appId: '1:222422545919:ios:8c610d5291fe735641e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    storageBucket: 'development-e5282.appspot.com',
    iosBundleId: 'org.shelterpartner.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPY-O2MZPBoXwQPcA4VIih0nrpmYyLEUc',
    appId: '1:222422545919:ios:8c610d5291fe735641e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    storageBucket: 'development-e5282.appspot.com',
    iosBundleId: 'org.shelterpartner.dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlISw9Omgjk3rsfw0ad-EqrBhLaCJiaME',
    appId: '1:222422545919:ios:8c610d5291fe735641e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    authDomain: 'development-e5282.firebaseapp.com',
    storageBucket: 'development-e5282.appspot.com',
  );
}
