// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZs0WVeZt91hc4fQtfuTg4kY4-bFq9qw',
    appId: '1:222422545919:web:6c595ab40b37a49e41e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    authDomain: 'development-e5282.firebaseapp.com',
    storageBucket: 'development-e5282.appspot.com',
    measurementId: 'G-8SNYDE7ZFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9qQTAJ1K4S76jQEBO_kU4TzPkvrI1Y04',
    appId: '1:222422545919:android:44fb37af6aea11a441e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    storageBucket: 'development-e5282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqKPd59J83BCXIkUotrmh1hu7VySoN1r8',
    appId: '1:222422545919:ios:21dca52a4856aab041e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    storageBucket: 'development-e5282.appspot.com',
    iosBundleId: 'me.jareddanieljones.HumaneSociety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqKPd59J83BCXIkUotrmh1hu7VySoN1r8',
    appId: '1:222422545919:ios:21dca52a4856aab041e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    storageBucket: 'development-e5282.appspot.com',
    iosBundleId: 'me.jareddanieljones.HumaneSociety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQZs0WVeZt91hc4fQtfuTg4kY4-bFq9qw',
    appId: '1:222422545919:web:3d8279b4151d741041e3ca',
    messagingSenderId: '222422545919',
    projectId: 'development-e5282',
    authDomain: 'development-e5282.firebaseapp.com',
    storageBucket: 'development-e5282.appspot.com',
    measurementId: 'G-0MGZLKMRL2',
  );

}