name: Flutter Build

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: Flutter/shelter_partner

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos
        working-directory: Flutter/shelter_partner

      - name: Run tests
        run: flutter test --exclude-tags golden
        working-directory: Flutter/shelter_partner

      - name: Build Web
        run: flutter build web
        working-directory: Flutter/shelter_partner

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: Flutter/shelter_partner

      - name: Run tests with coverage
        run: flutter test --coverage
        working-directory: Flutter/shelter_partner
        continue-on-error: true

      - name: Generate coverage report
        run: dart coverage_report.dart
        working-directory: Flutter/shelter_partner
        if: always()
  build-windows:
    # Windows build is disabled due to use of dart:html, which is not supported on Windows.
    # To re-enable, remove dart:html imports from lib/main.dart and any other non-web files.
    if: false
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: Flutter/shelter_partner

      - name: Build Windows
        run: flutter build windows
        working-directory: Flutter/shelter_partner
  build-macos:
    # macOS build is disabled due to use of dart:html, which is not supported on macOS.
    # To re-enable, remove dart:html imports from lib/main.dart and any other non-web files.
    if: false
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: Flutter/shelter_partner

      - name: Build macOS
        run: flutter build macos
        working-directory: Flutter/shelter_partner
  build-ios:
    # iOS build is disabled due to use of dart:html, which is not supported on iOS.
    # To re-enable, remove dart:html imports from lib/main.dart and any other non-web files.
    if: false
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: Flutter/shelter_partner

      - name: Build iOS
        run: flutter build ios --no-codesign
        working-directory: Flutter/shelter_partner
  build-website-web:
    # Website build is disabled because the Website project does not currently compile.
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true

      - name: Install dependencies
        run: flutter pub get
        working-directory: Website

      - name: Build Web
        run: flutter build web
        working-directory: Website
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'
          cache: true
      - name: Install dependencies (shelter_partner)
        run: flutter pub get
        working-directory: Flutter/shelter_partner
      - name: Check Dart formatting (shelter_partner)
        run: |
          set +e
          dart format --output=none --set-exit-if-changed .
          if [ $? -ne 0 ]; then
            echo '::error::Dart formatting issues found in Flutter/shelter_partner.'
            echo 'To fix, run:'
            echo '  cd Flutter/shelter_partner && dart format .'
            echo 'cd Flutter/shelter_partner && dart format .' >> $GITHUB_WORKSPACE/format_fixes.txt
            exit_code=1
          fi
          set -e
        working-directory: Flutter/shelter_partner
      - name: Install dependencies (website)
        run: flutter pub get
        working-directory: Website
      - name: Check Dart formatting (website)
        run: |
          set +e
          dart format --output=none --set-exit-if-changed .
          if [ $? -ne 0 ]; then
            echo '::error::Dart formatting issues found in Website.'
            echo 'To fix, run:'
            echo '  cd Website && dart format .'
            echo 'cd Website && dart format .' >> $GITHUB_WORKSPACE/format_fixes.txt
            exit_code=1
          fi
          set -e
          exit ${exit_code:-0}
        working-directory: Website
      - name: Generate formatting patch
        if: always()
        run: |
          dart format Flutter/shelter_partner Website
          git diff HEAD > format.patch || true
          git checkout -- .
      - name: Upload formatting patch artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: formatting-patch
          path: format.patch
      - name: Summary of formatting fixes
        if: always()
        run: |
          if [ -f $GITHUB_WORKSPACE/format_fixes.txt ]; then
            echo '::error::Summary of formatting issues:'
            echo ''
            echo 'To fix all formatting issues, run the following commands:'
            cat $GITHUB_WORKSPACE/format_fixes.txt
          else
            echo 'All formatting checks passed.'
          fi
      - name: Check for autofixable Dart issues and upload patch if present (shelter_partner)
        run: |
          set +e
          dart fix --apply
          git diff > autofix.patch
          if [ -s autofix.patch ]; then
            echo '::error::Autofixable issues detected. Patch uploaded.'
            echo 'To fix, run:'
            echo '  cd Flutter/shelter_partner && dart fix --apply'
            echo 'cd Flutter/shelter_partner && dart fix --apply' >> $GITHUB_WORKSPACE/fix_fixes.txt
            exit 1
          else
            echo 'No autofixable issues found.'
          fi
          set -e
        working-directory: Flutter/shelter_partner
      - name: Upload autofix patch artifact (shelter_partner)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: autofix-patch-shelter_partner
          path: Flutter/shelter_partner/autofix.patch
      - name: Check for autofixable Dart issues and upload patch if present (website)
        run: |
          set +e
          dart fix --apply
          git diff > autofix.patch
          if [ -s autofix.patch ]; then
            echo '::error::Autofixable issues detected. Patch uploaded.'
            echo 'To fix, run:'
            echo '  cd Website && dart fix --apply'
            echo 'cd Website && dart fix --apply' >> $GITHUB_WORKSPACE/fix_fixes.txt
            exit 1
          else
            echo 'No autofixable issues found.'
          fi
          set -e
        working-directory: Website
      - name: Upload autofix patch artifact (website)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: autofix-patch-website
          path: Website/autofix.patch
